import com.superflow.data.model.*
import com.superflow.domain.Capabilities
import com.superflow.domain.Serial
import org.json.JSONArray
import org.json.JSONObject

var pass = 0
var fail = 0
fun check(n: String, c: Boolean) { if (c) { pass++; println("  ok   $n") } else { fail++; println("  FAIL $n") } }
fun eq(n: String, a: Any?, b: Any?) = check("$n  ($a == $b)", a == b)

/** Core Growth Systems: nested-field serialization round-trips. */
fun main() {
    println("Ladder evolution serialization")
    val ladder = listOf(
        LadderEvolution(level = Level.STANDARD, previousText = "Walk 10 min",
            newText = "Walk 15 min", reason = "14 consecutive standards", date = "2026-07-01")
    )
    val h = Habit(title = "Walk", ladderHistory = ladder, stretchCount = 3,
        consecutiveStandards = 5, estimatedMinutes = 12, difficultyRating = 4,
        rewardSatisfaction = 4, rewardLastRated = "2026-07-10",
        reframeHelpful = true, bundleEffectiveness = 3, frictionPlanActive = true,
        environmentPrepReminderTime = "21:00", lastDifficultyRating = 2)
    val hJson = Serial.of(h)
    val hBack = Serial.habit(hJson)
    eq("ladder history round-trip", hBack.ladderHistory.size, 1)
    eq("ladder level", hBack.ladderHistory.first().level, Level.STANDARD)
    eq("ladder newText", hBack.ladderHistory.first().newText, "Walk 15 min")
    eq("ladder reason", hBack.ladderHistory.first().reason, "14 consecutive standards")
    eq("stretchCount", hBack.stretchCount, 3)
    eq("consecutiveStandards", hBack.consecutiveStandards, 5)
    eq("estimatedMinutes", hBack.estimatedMinutes, 12)
    eq("difficultyRating", hBack.difficultyRating, 4)
    eq("rewardSatisfaction", hBack.rewardSatisfaction, 4)
    eq("rewardLastRated", hBack.rewardLastRated, "2026-07-10")
    eq("reframeHelpful", hBack.reframeHelpful, true)
    eq("bundleEffectiveness", hBack.bundleEffectiveness, 3)
    eq("frictionPlanActive", hBack.frictionPlanActive, true)
    eq("environmentPrepReminderTime", hBack.environmentPrepReminderTime, "21:00")
    eq("lastDifficultyRating", hBack.lastDifficultyRating, 2)

    println("Check-in rich data serialization")
    val ci = CheckIn(habitId = "h1", date = "2026-07-01", result = CheckInResult.DONE,
        level = Level.STRETCH, contextTags = listOf("good sleep", "high energy"),
        actualAmount = 12.0, actualDurationMinutes = 45, qualityRating = 3,
        difficultyRating = 2, missReason = "time", missReasonDetail = "meeting ran long")
    val ciJson = Serial.of(ci)
    val ciBack = Serial.checkIn(ciJson)
    eq("contextTags round-trip", ciBack.contextTags, listOf("good sleep", "high energy"))
    eq("actualAmount", ciBack.actualAmount, 12.0)
    eq("actualDurationMinutes", ciBack.actualDurationMinutes, 45)
    eq("qualityRating", ciBack.qualityRating, 3)
    eq("difficultyRating", ciBack.difficultyRating, 2)
    eq("missReason", ciBack.missReason, "time")
    eq("missReasonDetail", ciBack.missReasonDetail, "meeting ran long")

    println("Goal milestones serialization")
    val goal = Goal(title = "Run a 5K", outcomeMetric = "km",
        currentMetricValue = 3.0, metricUnit = "km",
        milestones = listOf(
            GoalMilestone(title = "Walk 1km", achieved = true, achievedDate = "2026-06-01"),
            GoalMilestone(title = "Walk 3km"),
            GoalMilestone(title = "Run 5km", linkedHabitIds = listOf("h1", "h2"))
        ))
    val gJson = Serial.of(goal)
    val gBack = Serial.goal(gJson)
    eq("milestones count", gBack.milestones.size, 3)
    eq("first achieved", gBack.milestones[0].achieved, true)
    eq("first achievedDate", gBack.milestones[0].achievedDate, "2026-06-01")
    eq("third linked habits", gBack.milestones[2].linkedHabitIds, listOf("h1", "h2"))
    eq("currentMetricValue", gBack.currentMetricValue, 3.0)
    eq("metricUnit", gBack.metricUnit, "km")

    println("Identity evolution serialization")
    val identity = Identity(statement = "Someone who moves daily",
        evolutionHistory = listOf(
            IdentityEvolution(previousStatement = "Someone who wants to move",
                newStatement = "Someone who moves daily",
                reason = "100 votes", votesAtEvolution = 100, date = "2026-05-01")
        ), isPrimary = true)
    val iJson = Serial.of(identity)
    val iBack = Serial.identity(iJson)
    eq("evolution history count", iBack.evolutionHistory.size, 1)
    eq("prev statement", iBack.evolutionHistory[0].previousStatement, "Someone who wants to move")
    eq("votes at evolution", iBack.evolutionHistory[0].votesAtEvolution, 100)
    eq("isPrimary", iBack.isPrimary, true)

    println("Review action items serialization")
    val review = Review(kind = ReviewKind.WEEKLY, periodLabel = "Week of Aug 17",
        autoGeneratedData = "87% consistency, strongest: Walk",
        actionItems = listOf(
            ReviewActionItem(text = "Shrink Journal to 5 min", linkedCommand = "{\"command\":\"update_habit\"}"),
            ReviewActionItem(text = "Move Meditate to morning", completed = true,
                completedDate = "2026-08-18", outcome = "Did it, worked")
        ), previousReviewId = "rev-1")
    val rJson = Serial.of(review)
    val rBack = Serial.review(rJson)
    eq("action items count", rBack.actionItems.size, 2)
    eq("autoGeneratedData", rBack.autoGeneratedData, "87% consistency, strongest: Walk")
    eq("first text", rBack.actionItems[0].text, "Shrink Journal to 5 min")
    eq("first linkedCommand", rBack.actionItems[0].linkedCommand, "{\"command\":\"update_habit\"}")
    eq("second completed", rBack.actionItems[1].completed, true)
    eq("second outcome", rBack.actionItems[1].outcome, "Did it, worked")
    eq("previousReviewId", rBack.previousReviewId, "rev-1")

    println("Focus item serialization")
    val focus = FocusItem(date = "2026-08-19", habitId = "h1", title = "Walk",
        done = false, isPriority = true, goalId = "g1", estimatedMinutes = 30,
        carryOverCount = 2)
    val fJson = Serial.of(focus)
    val fBack = Serial.focus(fJson)
    eq("isPriority", fBack.isPriority, true)
    eq("goalId", fBack.goalId, "g1")
    eq("estimatedMinutes", fBack.estimatedMinutes, 30)
    eq("carryOverCount", fBack.carryOverCount, 2)

    println("Obstacle plan serialization")
    val obs = ObstaclePlan(habitId = "h1", ifText = "It rains", thenText = "Stretch indoors",
        category = "weather", timesUsed = 3, lastUsed = "2026-08-18", effectiveness = 4)
    val oJson = Serial.of(obs)
    val oBack = Serial.obstacle(oJson)
    eq("category", oBack.category, "weather")
    eq("timesUsed", oBack.timesUsed, 3)
    eq("lastUsed", oBack.lastUsed, "2026-08-18")
    eq("effectiveness", oBack.effectiveness, 4)

    println("Flow & flow step serialization")
    val flow = Flow(title = "Morning", anchor = "Wake up", estimatedMinutes = 25,
        completionCount = 4, partialCount = 2)
    val f2Json = Serial.of(flow)
    val f2Back = Serial.flow(f2Json)
    eq("estimatedMinutes", f2Back.estimatedMinutes, 25)
    eq("completionCount", f2Back.completionCount, 4)
    eq("partialCount", f2Back.partialCount, 2)
    val step = FlowStep(flowId = "f1", habitId = "h1", title = "Walk",
        durationMinutes = 10, isBreakpoint = true)
    val sJson = Serial.of(step)
    val sBack = Serial.flowStep(sJson)
    eq("durationMinutes", sBack.durationMinutes, 10)
    eq("isBreakpoint", sBack.isBreakpoint, true)

    println("System template fields")
    val sys = Sys(title = "Morning Movement", templateId = "morning_routine",
        reviewFrequency = "weekly")
    val syJson = Serial.of(sys)
    val syBack = Serial.system(syJson)
    eq("templateId", syBack.templateId, "morning_routine")
    eq("reviewFrequency", syBack.reviewFrequency, "weekly")

    println("Ladder level text with evolved ladder")
    val evolved = Habit(title = "Walk", tinyStart = "Shoes on",
        standardVersion = "Walk 10 min")
    eq("levelText standard", evolved.levelText(Level.STANDARD), "Walk 10 min")
    eq("levelText tiny fallback", evolved.levelText(Level.TINY), "Shoes on")
    eq("levelText stretch fallback", evolved.levelText(Level.STRETCH), "Walk 10 min")

    println("Model defaults for growth fields")
    val fresh = Habit(title = "Walk")
    eq("default estimatedMinutes", fresh.estimatedMinutes, 5)
    eq("default difficultyRating", fresh.difficultyRating, 3)
    eq("default frictionPlanActive", fresh.frictionPlanActive, false)
    eq("default ladderHistory empty", fresh.ladderHistory.size, 0)
    val freshCi = CheckIn(habitId = "h", date = "2026-01-01", result = CheckInResult.DONE)
    eq("default contextTags empty", freshCi.contextTags.size, 0)
    eq("default missReason null", freshCi.missReason, null)
    val freshFocus = FocusItem(date = "2026-01-01", habitId = "h", title = "t")
    eq("default isPriority", freshFocus.isPriority, false)
    eq("default carryOverCount", freshFocus.carryOverCount, 0)
    val freshSys = Sys(title = "S")
    eq("default reviewFrequency", freshSys.reviewFrequency, "monthly")
    eq("default templateId", freshSys.templateId, null)
    val freshGoal = Goal(title = "G")
    eq("default milestones empty", freshGoal.milestones.size, 0)
    val freshIdentity = Identity(statement = "s")
    eq("default isPrimary", freshIdentity.isPrimary, true)
    eq("default evolutionHistory empty", freshIdentity.evolutionHistory.size, 0)

    println("System templates catalog")
    val templates = Capabilities.systemTemplates()
    check("has five templates", templates.size == 5)
    check("has morning routine", templates.any { it.first == "morning_routine" })
    check("has evening wind-down", templates.any { it.first == "evening_wind_down" })

    println()
    println("GrowthTest: $pass passed, $fail failed")
    if (fail > 0) kotlin.system.exitProcess(1)
}
