package com.superflow.design

/**
 * Tonal ramps as ARGB integers.
 *
 * GENERATED by tools/gen_palettes.py from the XML colour resources. Do not
 * edit by hand: change the XML and regenerate, or the View layer and the
 * Compose layer will disagree about what "Forest" looks like.
 *
 * Tone numbers follow the Material convention - 10 is near-black, 99 is
 * near-white, and the same tone has comparable perceived lightness across
 * every ramp, so a contrast ratio that holds in one palette holds in all of
 * them. That property is what makes [Ramps.role] safe to write once rather
 * than per palette.
 *
 * Values are 0xAARRGGBB. Kotlin has no unsigned literal that fits in an Int,
 * so each is written as a signed literal via toInt().
 */
object Ramps {

    /** `sf_amber_*`, 9 steps. */
    val amber = mapOf(
        10 to 0xFF2B1600.toInt(),
        20 to 0xFF472600.toInt(),
        30 to 0xFF663800.toInt(),
        40 to 0xFF8A4E0B.toInt(),
        50 to 0xFFB4703A.toInt(),
        70 to 0xFFE0A578.toInt(),
        80 to 0xFFF2C6A2.toInt(),
        90 to 0xFFFAE3D0.toInt(),
        95 to 0xFFFDF1E6.toInt(),
    )

    /** `sf_dusk_rose_*`, 11 steps. */
    val duskRose = mapOf(
        10 to 0xFF291618.toInt(),
        20 to 0xFF4C2527.toInt(),
        30 to 0xFF6E3639.toInt(),
        40 to 0xFF93474C.toInt(),
        50 to 0xFFB15F64.toInt(),
        60 to 0xFFC17F83.toInt(),
        70 to 0xFFD09FA2.toInt(),
        80 to 0xFFE0BFC1.toInt(),
        90 to 0xFFEEDFE0.toInt(),
        95 to 0xFFF5EFF0.toInt(),
        99 to 0xFFFDFCFC.toInt(),
    )

    /** `sf_dusk_violet_*`, 11 steps. */
    val duskViolet = mapOf(
        10 to 0xFF1D1A27.toInt(),
        20 to 0xFF342C48.toInt(),
        30 to 0xFF4C4069.toInt(),
        40 to 0xFF65568C.toInt(),
        50 to 0xFF7E6EA7.toInt(),
        60 to 0xFF968AB7.toInt(),
        70 to 0xFFB0A6C9.toInt(),
        80 to 0xFFCAC3DA.toInt(),
        90 to 0xFFE4E1EB.toInt(),
        95 to 0xFFF1F0F4.toInt(),
        99 to 0xFFFCFCFD.toInt(),
    )

    /** `sf_forest_green_*`, 11 steps. */
    val forestGreen = mapOf(
        10 to 0xFF0F1F18.toInt(),
        20 to 0xFF173628.toInt(),
        30 to 0xFF224F3B.toInt(),
        40 to 0xFF2D694E.toInt(),
        50 to 0xFF388563.toInt(),
        60 to 0xFF44A178.toInt(),
        70 to 0xFF62BC94.toInt(),
        80 to 0xFF97D3B9.toInt(),
        90 to 0xFFD0E8DD.toInt(),
        95 to 0xFFEBF3EF.toInt(),
        99 to 0xFFFBFCFC.toInt(),
    )

    /** `sf_forest_olive_*`, 11 steps. */
    val forestOlive = mapOf(
        10 to 0xFF1E1C0D.toInt(),
        20 to 0xFF353113.toInt(),
        30 to 0xFF4E471C.toInt(),
        40 to 0xFF685F26.toInt(),
        50 to 0xFF837830.toInt(),
        60 to 0xFF9F923A.toInt(),
        70 to 0xFFBCAC46.toInt(),
        80 to 0xFFD2C884.toInt(),
        90 to 0xFFE7E3C8.toInt(),
        95 to 0xFFF2F1E8.toInt(),
        99 to 0xFFFCFCFB.toInt(),
    )

    /** `sf_green_*`, 11 steps. */
    val green = mapOf(
        10 to 0xFF06231A.toInt(),
        20 to 0xFF0C3A2B.toInt(),
        30 to 0xFF17513C.toInt(),
        40 to 0xFF2E6B50.toInt(),
        50 to 0xFF3A7D5C.toInt(),
        60 to 0xFF56997A.toInt(),
        70 to 0xFF78B598.toInt(),
        80 to 0xFF9FD2B8.toInt(),
        90 to 0xFFC8E9D8.toInt(),
        95 to 0xFFE2F4EB.toInt(),
        99 to 0xFFF5FCF8.toInt(),
    )

    /** `sf_indigo_*`, 3 steps. */
    val indigo = mapOf(
        40 to 0xFF3F5A8A.toInt(),
        80 to 0xFFB2C6EC.toInt(),
        90 to 0xFFD8E3F8.toInt(),
    )

    /** `sf_mono_stone_*`, 11 steps. */
    val monoStone = mapOf(
        10 to 0xFF1C1B1A.toInt(),
        20 to 0xFF32302E.toInt(),
        30 to 0xFF494643.toInt(),
        40 to 0xFF625E59.toInt(),
        50 to 0xFF7C7671.toInt(),
        60 to 0xFF95908B.toInt(),
        70 to 0xFFAEAAA7.toInt(),
        80 to 0xFFC9C6C3.toInt(),
        90 to 0xFFE3E2E1.toInt(),
        95 to 0xFFF1F1F0.toInt(),
        99 to 0xFFFCFCFC.toInt(),
    )

    /** `sf_neutral_*`, 14 steps. */
    val neutral = mapOf(
        0 to 0xFF000000.toInt(),
        10 to 0xFF1C1B18.toInt(),
        20 to 0xFF31302C.toInt(),
        30 to 0xFF48463F.toInt(),
        40 to 0xFF605D55.toInt(),
        50 to 0xFF79756C.toInt(),
        60 to 0xFF938F85.toInt(),
        70 to 0xFFAEA99F.toInt(),
        80 to 0xFFCAC5BA.toInt(),
        90 to 0xFFE7E2D6.toInt(),
        94 to 0xFFF1ECE0.toInt(),
        96 to 0xFFF7F2E7.toInt(),
        98 to 0xFFFBF7EE.toInt(),
        100 to 0xFFFFFFFF.toInt(),
    )

    /** `sf_ocean_coral_*`, 11 steps. */
    val oceanCoral = mapOf(
        10 to 0xFF2B1610.toInt(),
        20 to 0xFF4F2417.toInt(),
        30 to 0xFF733421.toInt(),
        40 to 0xFF99452C.toInt(),
        50 to 0xFFC15738.toInt(),
        60 to 0xFFD17960.toInt(),
        70 to 0xFFDD9C88.toInt(),
        80 to 0xFFE8BDB0.toInt(),
        90 to 0xFFF1DFD9.toInt(),
        95 to 0xFFF6EFED.toInt(),
        99 to 0xFFFDFCFC.toInt(),
    )

    /** `sf_ocean_teal_*`, 11 steps. */
    val oceanTeal = mapOf(
        10 to 0xFF091E22.toInt(),
        20 to 0xFF0C353C.toInt(),
        30 to 0xFF114E58.toInt(),
        40 to 0xFF176775.toInt(),
        50 to 0xFF1D8293.toInt(),
        60 to 0xFF239EB3.toInt(),
        70 to 0xFF29BBD4.toInt(),
        80 to 0xFF76D4E4.toInt(),
        90 to 0xFFC5E9EF.toInt(),
        95 to 0xFFE7F3F5.toInt(),
        99 to 0xFFFBFCFD.toInt(),
    )

    /** Flat (non-ramp) colours, day values, by resource name. */
    val flatDay: Map<String, Int> = mapOf(
        "level_minimum" to 0xFF78B598.toInt(),
        "level_standard" to 0xFF3A7D5C.toInt(),
        "level_stretch" to 0xFF17513C.toInt(),
        "level_tiny" to 0xFF9FD2B8.toInt(),
        "sf_caution" to 0xFFC1674F.toInt(),
        "sf_caution_container" to 0xFFF7DED4.toInt(),
        "sf_celebration" to 0xFFC59A3D.toInt(),
        "sf_celebration_container" to 0xFFF7EBCE.toInt(),
        "sf_dark_midnight_background" to 0xFF0A0E1A.toInt(),
        "sf_dark_midnight_outline_variant" to 0xFF2E3547.toInt(),
        "sf_dark_midnight_surface" to 0xFF121624.toInt(),
        "sf_dark_midnight_surface_variant" to 0xFF1D2233.toInt(),
        "sf_dark_oled_background" to 0xFF000000.toInt(),
        "sf_dark_oled_outline_variant" to 0xFF2B2B2B.toInt(),
        "sf_dark_oled_surface" to 0xFF0D0D0D.toInt(),
        "sf_dark_oled_surface_variant" to 0xFF1A1A1A.toInt(),
        "sf_dark_warm_background" to 0xFF14130F.toInt(),
        "sf_dark_warm_outline_variant" to 0xFF3A382F.toInt(),
        "sf_dark_warm_surface" to 0xFF1C1B17.toInt(),
        "sf_dark_warm_surface_variant" to 0xFF2A2823.toInt(),
        "sf_energy_1" to 0xFF6B7F94.toInt(),
        "sf_energy_2" to 0xFF7E9299.toInt(),
        "sf_energy_3" to 0xFF95A08C.toInt(),
        "sf_energy_4" to 0xFFB39A6E.toInt(),
        "sf_energy_5" to 0xFFD19A55.toInt(),
        "sf_error_40" to 0xFF9B4A3C.toInt(),
        "sf_error_90" to 0xFFF7DAD4.toInt(),
        "sf_info" to 0xFF3F5A8A.toInt(),
        "sf_info_container" to 0xFFD8E3F8.toInt(),
        "sf_on_success" to 0xFFFFFFFF.toInt(),
        "sf_on_warning" to 0xFFFFFFFF.toInt(),
        "sf_recovery" to 0xFF5C7F9B.toInt(),
        "sf_recovery_container" to 0xFFDCE8F1.toInt(),
        "sf_skeleton_base" to 0xFFEDE8DC.toInt(),
        "sf_skeleton_highlight" to 0xFFF9F5EC.toInt(),
        "sf_success" to 0xFF3A7D5C.toInt(),
        "sf_success_container" to 0xFFC8E9D8.toInt(),
        "sf_warning" to 0xFFB4703A.toInt(),
        "sf_warning_container" to 0xFFFAE3D0.toInt(),
        "state_empty" to 0xFFE7E2D6.toInt(),
        "state_missed" to 0xFFF2C6A2.toInt(),
        "state_skipped" to 0xFFCAC5BA.toInt(),
    )

    /** Flat (non-ramp) colours, night values, by resource name. */
    val flatNight: Map<String, Int> = mapOf(
        "level_minimum" to 0xFF56997A.toInt(),
        "level_standard" to 0xFF78B598.toInt(),
        "level_stretch" to 0xFF9FD2B8.toInt(),
        "level_tiny" to 0xFF3E6B57.toInt(),
        "sf_caution" to 0xFFEFB4A8.toInt(),
        "sf_caution_container" to 0xFF7A2E22.toInt(),
        "sf_celebration" to 0xFFE8C77E.toInt(),
        "sf_celebration_container" to 0xFF5C4718.toInt(),
        "sf_dark_midnight_background" to 0xFF0A0E1A.toInt(),
        "sf_dark_midnight_outline_variant" to 0xFF2E3547.toInt(),
        "sf_dark_midnight_surface" to 0xFF121624.toInt(),
        "sf_dark_midnight_surface_variant" to 0xFF1D2233.toInt(),
        "sf_dark_oled_background" to 0xFF000000.toInt(),
        "sf_dark_oled_outline_variant" to 0xFF2B2B2B.toInt(),
        "sf_dark_oled_surface" to 0xFF0D0D0D.toInt(),
        "sf_dark_oled_surface_variant" to 0xFF1A1A1A.toInt(),
        "sf_dark_warm_background" to 0xFF14130F.toInt(),
        "sf_dark_warm_outline_variant" to 0xFF3A382F.toInt(),
        "sf_dark_warm_surface" to 0xFF1C1B17.toInt(),
        "sf_dark_warm_surface_variant" to 0xFF2A2823.toInt(),
        "sf_energy_1" to 0xFF8FA3B8.toInt(),
        "sf_energy_2" to 0xFF9DB3BA.toInt(),
        "sf_energy_3" to 0xFFB2BCA8.toInt(),
        "sf_energy_4" to 0xFFCFB88A.toInt(),
        "sf_energy_5" to 0xFFE5B673.toInt(),
        "sf_error_40" to 0xFF9B4A3C.toInt(),
        "sf_error_90" to 0xFFF7DAD4.toInt(),
        "sf_info" to 0xFFB2C6EC.toInt(),
        "sf_info_container" to 0xFF27406B.toInt(),
        "sf_on_success" to 0xFF06231A.toInt(),
        "sf_on_warning" to 0xFF2B1600.toInt(),
        "sf_recovery" to 0xFFA9C4D8.toInt(),
        "sf_recovery_container" to 0xFF33495C.toInt(),
        "sf_skeleton_base" to 0xFF26251F.toInt(),
        "sf_skeleton_highlight" to 0xFF332F28.toInt(),
        "sf_success" to 0xFF9FD2B8.toInt(),
        "sf_success_container" to 0xFF17513C.toInt(),
        "sf_warning" to 0xFFF2C6A2.toInt(),
        "sf_warning_container" to 0xFF663800.toInt(),
        "state_empty" to 0xFF2A2823.toInt(),
        "state_missed" to 0xFF7A5433.toInt(),
        "state_skipped" to 0xFF3A382F.toInt(),
    )

    /**
     * A flat colour by resource name, for the given mode.
     *
     * Mirrors resource resolution: the night table falls back to the day
     * value when values-night does not override the name.
     */
    fun flat(name: String, isDark: Boolean): Int =
        (if (isDark) flatNight else flatDay)[name]
            ?: error("unknown colour $name")

    /** Every ramp, by resource name, for exhaustive tests. */
    val all: Map<String, Map<Int, Int>> = mapOf(
        "sf_amber" to amber,
        "sf_dusk_rose" to duskRose,
        "sf_dusk_violet" to duskViolet,
        "sf_forest_green" to forestGreen,
        "sf_forest_olive" to forestOlive,
        "sf_green" to green,
        "sf_indigo" to indigo,
        "sf_mono_stone" to monoStone,
        "sf_neutral" to neutral,
        "sf_ocean_coral" to oceanCoral,
        "sf_ocean_teal" to oceanTeal,
    )
}
