#!/usr/bin/env python3
"""
Generates design/Ramps.kt from the XML colour resources.

The Compose layer needs the tonal ramps as Kotlin values; the View layer
needs them as XML resources. Hand-maintaining both is how a palette ends up
subtly different depending on which rendering path drew it, and that class
of bug is invisible in review because both files look plausible.

So the XML stays the source of truth (aapt2 validates it, check_res.py
cross-checks it, and the night variants live beside it) and this script
projects it into Kotlin. Run it after changing any ramp:

    python3 tools/gen_palettes.py

The output is checked in - the build has no code generation step - and
tools/check_generated.py verifies it is current, so a stale Ramps.kt fails
the test run rather than shipping.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app/src/main/kotlin/com/superflow/design/Ramps.kt"

# Ramp sources. Calm's ramps predate the palette system and live in the base
# colours file under shorter names.
# Flat (non-ramp) colours the Compose layer needs as Kotlin values. Same
# rule as the ramps: XML is the source of truth, this is the projection.
FLAT_SOURCES = [
    "app/src/main/res/values/colors.xml",
    "app/src/main/res/values/colors_semantic.xml",
]
FLAT_PREFIXES = (
    "sf_error_",      # error roles, referenced by name from the base theme
    "sf_dark_",       # dark flavour surfaces
    "sf_success", "sf_on_success", "sf_warning", "sf_on_warning",
    "sf_caution", "sf_info", "sf_recovery", "sf_celebration",
    "sf_energy_", "sf_skeleton_",
    "state_", "level_",
)
# Night overrides for the same flat names.
FLAT_NIGHT = [
    "app/src/main/res/values-night/colors.xml",
    "app/src/main/res/values-night/colors_semantic.xml",
]

SOURCES = [
    ("app/src/main/res/values/colors.xml", ["sf_green", "sf_amber", "sf_neutral", "sf_indigo"]),
    (
        "app/src/main/res/values/colors_palettes.xml",
        [
            "sf_forest_green",
            "sf_forest_olive",
            "sf_ocean_teal",
            "sf_ocean_coral",
            "sf_dusk_violet",
            "sf_dusk_rose",
            "sf_mono_stone",
        ],
    ),
]

HEADER = '''package com.superflow.design

/**
 * Tonal ramps as ARGB integers.
 *
 * GENERATED by tools/gen_palettes.py from the XML colour resources. Do not
 * edit by hand: change the XML and regenerate, or the View layer and the
 * Compose layer will disagree about what "Forest" looks like.
 *
 * Tone numbers follow the Material convention - 10 is near-black, 99 is
 * near-white, and the same tone has comparable perceived lightness across
 * every ramp, so a contrast ratio that holds in one palette holds in all of
 * them. That property is what makes [Ramps.role] safe to write once rather
 * than per palette.
 *
 * Values are 0xAARRGGBB. Kotlin has no unsigned literal that fits in an Int,
 * so each is written as a signed literal via toInt().
 */
object Ramps {
'''


def parse_flat(paths):
    """Flat colour names -> hex, later files winning."""
    out = {}
    for path in paths:
        f = ROOT / path
        if not f.is_file():
            continue
        for m in re.finditer(
            r'name="([a-z0-9_]+)"\s*>\s*(#[0-9A-Fa-f]{6,8})\s*<', f.read_text()
        ):
            name, value = m.group(1), m.group(2).lstrip("#")
            if len(value) == 6:
                value = "FF" + value
            if name.startswith(FLAT_PREFIXES):
                out[name] = value.upper()
    return out


def kt_name(resource_name):
    parts = resource_name.removeprefix("sf_").split("_")
    name = parts[0] + "".join(p.capitalize() for p in parts[1:])
    return name


def parse(path, prefixes):
    text = (ROOT / path).read_text()
    found = {}
    for m in re.finditer(r'name="(sf_[a-z_]+?)_(\d+)"\s*>\s*(#[0-9A-Fa-f]{8})\s*<', text):
        name, tone, value = m.group(1), int(m.group(2)), m.group(3)
        if name in prefixes:
            found.setdefault(name, {})[tone] = value
    return found


def main():
    ramps = {}
    for path, prefixes in SOURCES:
        got = parse(path, prefixes)
        for name in prefixes:
            if name not in got:
                print(f"missing ramp {name} in {path}")
                sys.exit(1)
        ramps.update(got)

    lines = [HEADER]
    for name in sorted(ramps):
        tones = ramps[name]
        kt = "".join(part.capitalize() for part in name[len("sf_"):].split("_"))
        kt = kt[0].lower() + kt[1:]
        lines.append(f"    /** `{name}_*`, {len(tones)} steps. */")
        lines.append(f"    val {kt} = mapOf(")
        for tone in sorted(tones):
            argb = tones[tone].lstrip("#").upper()
            lines.append(f"        {tone} to 0x{argb}.toInt(),")
        lines.append("    )")
        lines.append("")

    # ---- flat colours, day and night
    day = parse_flat(FLAT_SOURCES)
    night = dict(day)
    night.update(parse_flat(FLAT_NIGHT))

    for label, table in (("day", day), ("night", night)):
        lines.append(f"    /** Flat (non-ramp) colours, {label} values, by resource name. */")
        lines.append(f"    val flat{label.capitalize()}: Map<String, Int> = mapOf(")
        for name in sorted(table):
            lines.append(f'        "{name}" to 0x{table[name]}.toInt(),')
        lines.append("    )")
        lines.append("")

    lines.append("    /**")
    lines.append("     * A flat colour by resource name, for the given mode.")
    lines.append("     *")
    lines.append("     * Mirrors resource resolution: the night table falls back to the day")
    lines.append("     * value when values-night does not override the name.")
    lines.append("     */")
    lines.append("    fun flat(name: String, isDark: Boolean): Int =")
    lines.append("        (if (isDark) flatNight else flatDay)[name]")
    lines.append('            ?: error("unknown colour $name")')
    lines.append("")

    names = sorted(ramps)
    lines.append("    /** Every ramp, by resource name, for exhaustive tests. */")
    lines.append("    val all: Map<String, Map<Int, Int>> = mapOf(")
    for name in names:
        kt = "".join(part.capitalize() for part in name[len("sf_"):].split("_"))
        kt = kt[0].lower() + kt[1:]
        lines.append(f'        "{name}" to {kt},')
    lines.append("    )")
    lines.append("}")

    OUT.write_text("\n".join(lines) + "\n")
    total = sum(len(v) for v in ramps.values())
    print(
        f"==> wrote {OUT.relative_to(ROOT)}: {len(ramps)} ramps, {total} tones, "
        f"{len(day)} flat colours"
    )


if __name__ == "__main__":
    main()
